#ifndef _ERRORS_H
#define _ERRORS_H

#include "Arduino.h"

enum errorCodes
{
    SUCCESS = 0,

    LENS_PORT_CLK_PULL_DOWN_TIMEOUT,
    LENS_PORT_CLK_RELEASE_TIMEOUT,
    LENS_PORT_SPI_BUFFER_TOO_SMALL,
    LENS_PORT_NO_ANSWER_AVAILABLE,

    LENS_INIT_BAD_CR_LENGTH,
    LENS_INIT_BAD_CR_RESPONSE,
    LENS_INIT_BAD_FL,
    LENS_INIT_SLOW_CR_FAILED,

    UI_MSG_BUFFER_EMPTY,

    UTILS_TOO_BIT_BIT_OF_BYTE,

    FOCUS_MOVE_TIMEOUT
};

String errorCodeToString(errorCodes theErrorCode);

#endif //_ERRORS_H